spring:
  data:
    mongodb:
      username: pratham
      password: pratham
      host: localhost
      port: 27017
      database: customer
      authentication-database: admin
server:
  port: 8090
